export const toolbar: string;
export const button: string;
export const buttonContent: string;
export const buttonIcon: string;
export const disabled: string;
export const container: string;
export const styl: string;
export const inputElement: string;
export const focused: string;