#!/usr/bin/env node

// Get file names to transform
const fs = require('fs')
const files = process.argv.slice(2)

// console.log(files)

const name_re = /(@keyframes\s+|\.)([$_a-zA-Z][$_a-zA-Z0-9-]*)/gim

for (var filename of files) {
  var file = fs.readFileSync(filename, 'utf-8')
  var match = null
  var found = {}
  var res = []
  while ((match = name_re.exec(file))) {
    var ident = toCamelCase(match[2])

    if (found[ident]) continue
    found[ident] = true

    res.push(`export const ${ident}: string;`)
    // console.log(match[2], toCamelCase(match[2]))
  }
  console.log(`=> writing ${filename}.d.ts`)
  fs.writeFileSync(`${filename}.d.ts`, res.join('\n'), {encoding: 'utf-8'})
}


function toCamelCase(str) {
  return str.replace(/-[\w]/g, repl => repl[1].toUpperCase())
}